{% set version = "0.6.5" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-sads
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sads_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sads/sads_{{ version }}.tar.gz
  sha256: 67ee6faede81b1161b8bf8e3b606c33f10d2e24d8ace7d54a78e9cb022a9099d

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-guilds                   # [build_platform != target_platform]
    - r-mass                     # [build_platform != target_platform]
    - r-vgam                     # [build_platform != target_platform]
    - r-bbmle >=1.0.19           # [build_platform != target_platform]
    - r-poilog                   # [build_platform != target_platform]
    - r-powerlaw                 # [build_platform != target_platform]
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib("c") }}          # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
    - {{ posix }}filesystem      # [win]
    - {{ posix }}make
    - {{ posix }}sed             # [win]
    - {{ posix }}coreutils       # [win]
    - {{ posix }}zip             # [win]
  host:
    - r-base
    - r-guilds
    - r-mass
    - r-vgam
    - r-bbmle >=1.0.19
    - r-poilog
    - r-powerlaw
  run:
    - r-base
    - r-guilds
    - r-mass
    - r-vgam
    - r-bbmle >=1.0.19
    - r-poilog
    - r-powerlaw

test:
  commands:
    - $R -e "library('sads')"           # [not win]
    - "\"%R%\" -e \"library('sads')\""  # [win]

about:
  home: http://piLaboratory.github.io/sads
  dev_url: https://github.com/piklprado/sads
  license: GPL-2.0-only
  summary: Maximum likelihood tools to fit and compare models of species abundance distributions and of species rank-abundance distributions.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - jenzopr
